models:
  - name: id_graph_users
    model_type: id_stitcher
    model_spec:
      entity_key: users
      time_grain: "hour"
      materialization:
        run_type: incremental
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
        - from: inputs/rsPages
  - name: knownUsers
    model_type: entity_cohort
    model_spec:
      extends: users/all
      time_grain: "day"
      materialization:
        output_type: table
      filter_pipeline:
        # exclude ids which don't have any other_id_type of email
        - type: exclude
          value: "{{ users.Var('id_type_email_count_daily') }} = 0"
  - name: user_profiles
    model_type: feature_table_model
    model_spec:
      time_grain: "day"
      entity_cohort: models/knownUsers
      features:
        - first_activity_time_weekly
        - first_activity_time_daily_mixed
        - campaign_name_daily
        - campaign_medium_daily
var_groups:
  - name: user_all_vars
    entity_key: users
    time_grain: "day"
    vars:
      - entity_var:
          name: id_type_email_count_daily
          from: models/id_graph_users
          select: sum(case when other_id_type = 'email' then 1 else 0 end)
  - name: user_known_weekly_vars
    entity_cohort: models/knownUsers
    time_grain: "week"
    vars:
      - entity_var:
          name: first_activity_time_weekly
          select: min(timestamp)
          from: inputs/rsPages # min timestamp from another table
          description: First Activity Time
  - name: user_known_daily_vars
    entity_cohort: models/knownUsers
    time_grain: "day"
    vars:
      - entity_var:
          name: first_activity_time_daily
          select: min(timestamp)
          from: inputs/rsTracks
          description: First Activity Time
          is_feature: False
      - entity_var:
          name: first_activity_time_daily_mixed
          select: least({{knownUsers.Var("first_activity_time_daily")}}, {{knownUsers.Var("first_activity_time_weekly")}})
          description: First Activity Time
      - entity_var:
          name: campaign_name_daily
          select: first_value(context_campaign_name)
          from: models/marketing_pages
          window:
            order_by:
              - timestamp desc
            frame_clause: rows between unbounded preceding and unbounded following
          description: context campaign name
      - entity_var:
          name: campaign_medium_daily
          select: first_value(context_campaign_medium)
          from: models/marketing_pages
          window:
            order_by:
              - timestamp desc
            frame_clause: rows between unbounded preceding and unbounded following
          description: context campaign medium
