models:
  - name: id_graph_users
    model_type: id_stitcher
    model_spec:
      entity_key: users
      materialization:
        run_type: incremental
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
        - from: inputs/rsPages
  - name: knownUsers
    model_type: entity_cohort
    model_spec:
      extends: users/all
      materialization:
        output_type: table
      filter_pipeline:
        - type: exclude
          value: "{{ users.Var('id_type_email_count') }} = 0"
  - name: user_profiles
    model_type: feature_table_model
    model_spec:
      entity_cohort: models/knownUsers
      features:
        - first_activity_time
        - campaign_name
        - campaign_medium
var_groups:
  - name: user_all_vars
    entity_key: users
    vars:
      - entity_var:
          name: id_type_email_count
          from: models/id_graph_users
          select: sum(case when other_id_type = 'email' then 1 else 0 end)
  - name: user_known_vars
    entity_cohort: models/knownUsers
    vars:
      - entity_var:
          name: first_activity_time
          select: min(timestamp)
          from: inputs/rsPages 
          description: First Activity Time
      - entity_var:
          name: campaign_name
          select: first_value(context_campaign_name)
          from: models/marketing_pages
          window:
            order_by:
              - timestamp desc
            frame_clause: rows between unbounded preceding and unbounded following
          description: context campaign name
      - entity_var:
          name: campaign_medium
          select: first_value(context_campaign_medium)
          from: models/marketing_pages
          window:
            order_by:
              - timestamp desc
            frame_clause: rows between unbounded preceding and unbounded following
          description: context campaign medium